env:
  ENVIRONMENT: production
  REGION: us-east-1
on: 
    push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use both secrets and environment vars 
        env:
          TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          echo "Deploying $ENVIRONMENT app to $REGION"
