name: ENV & SECRETS
env:
  ENVIRONMENT: production
  REGION: us-east-1
on: 
    workflow_run:
      workflows: ["CLI"]
      types:
        - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Use both secrets and environment vars 
        env:
          TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          echo "Deploying $ENVIRONMENT app to $REGION"
