name: Self Hosted Runner

on:
  workflow_run:
    workflows: ["ENV & SECRETS"]
    types:
      - completed

jobs:
  self-hosted-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    runs-on: self-hosted
    steps:
      - name: Print system info
        run: |
          echo "Running on self-hosted runner! after the env file"
          uname -a
