name: Test Self Hosted Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  self-hosted-job:
    runs-on: self-hosted
    steps:
      - name: Print system info
        run: |
          echo "Running on self-hosted runner!"
          uname -a
