name: Test Custom Composite Action

on: [push]

jobs:
  custom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom greet action
        uses: ./.github/actions/greetuser
        with:
          name: Dhanush
          organisation: "Blue-ocean"
